In [2]:
from transformers import BertModel, BertTokenizer
import torch

In [3]:
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
model = BertModel.from_pretrained("bert-base-uncased")

In [4]:
example_sentences = ["She is a MachineLearning Engineer and works in California", "I am a monster! Hahahaha"]

In [32]:
all_tokens = []
for sentence in example_sentences:
    tokens = tokenizer.tokenize(sentence)
    tokens = ['[CLS]'] + tokens + ['[SEP]']
    var_len = abs(len(tokens) - 20)
    tokens = tokens + ['[PAD]']*var_len
    print(len(sentence.split()), len(tokens))
    print(tokens)
    all_tokens.append(tokens)

9 20
['[CLS]', 'she', 'is', 'a', 'machine', '##lea', '##rn', '##ing', 'engineer', 'and', 'works', 'in', 'california', '[SEP]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]']
5 20
['[CLS]', 'i', 'am', 'a', 'monster', '!', 'ha', '##ha', '##ha', '##ha', '[SEP]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]', '[PAD]']


In [33]:
ids = []
for tokens in all_tokens:
    token_ids = tokenizer.convert_tokens_to_ids(tokens)
    ids.append(token_ids)

In [34]:
mask = []
for token_ids in ids:
    attention_mask = [1 if i!= 0 else 0 for i in token_ids] 
    mask.append(attention_mask)

In [35]:
ids, mask

([[101,
   2016,
   2003,
   1037,
   3698,
   19738,
   6826,
   2075,
   3992,
   1998,
   2573,
   1999,
   2662,
   102,
   0,
   0,
   0,
   0,
   0,
   0],
  [101,
   1045,
   2572,
   1037,
   6071,
   999,
   5292,
   3270,
   3270,
   3270,
   102,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0]],
 [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [38]:
mask = torch.tensor(mask)
mask.shape, mask

(torch.Size([2, 20]),
 tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]]))

In [39]:
ids = torch.tensor(ids)
ids.shape, ids

(torch.Size([2, 20]),
 tensor([[  101,  2016,  2003,  1037,  3698, 19738,  6826,  2075,  3992,  1998,
           2573,  1999,  2662,   102,     0,     0,     0,     0,     0,     0],
         [  101,  1045,  2572,  1037,  6071,   999,  5292,  3270,  3270,  3270,
            102,     0,     0,     0,     0,     0,     0,     0,     0,     0]]))

In [40]:
output = model(ids, mask)

In [41]:
output[0].shape, output[0]

(torch.Size([2, 20, 768]),
 tensor([[[-0.1925,  0.1684, -0.4252,  ..., -0.2599,  0.3736,  0.0529],
          [ 0.2417, -0.2748, -0.4909,  ...,  0.1372,  0.3408, -0.4655],
          [-0.0871,  0.0837,  0.2605,  ..., -0.4635, -0.0462,  0.2621],
          ...,
          [-0.2704, -0.0269, -0.3106,  ...,  0.4387,  0.5628, -0.4095],
          [-0.0849, -0.2977,  0.1915,  ..., -0.0258, -0.1268,  0.2498],
          [-0.1086, -0.2620,  0.0094,  ..., -0.0239, -0.1561,  0.4143]],
 
         [[ 0.0552,  0.3124,  0.0049,  ..., -0.3497,  0.1501,  0.4177],
          [ 0.3221,  0.5422, -0.1247,  ..., -0.0987,  0.7055,  0.2329],
          [ 0.3661,  0.6840,  0.1676,  ..., -0.3840,  0.7070,  0.0479],
          ...,
          [ 0.2076,  0.2493,  0.7378,  ...,  0.1297, -0.0354,  0.0881],
          [ 0.3487,  0.3229,  0.7750,  ...,  0.1336, -0.0592, -0.0942],
          [ 0.1594,  0.3179,  0.7994,  ...,  0.1152, -0.0669,  0.1130]]],
        grad_fn=<NativeLayerNormBackward0>))

In [42]:
output[1].shape, output[1]

(torch.Size([2, 768]),
 tensor([[-0.9531, -0.4914, -0.8872,  ..., -0.4155, -0.6854,  0.9550],
         [-0.9058, -0.4621, -0.8835,  ..., -0.6585, -0.7275,  0.9255]],
        grad_fn=<TanhBackward0>))