In [ ]:
# !pip install tensorflow==2.12.0
# !pip install tensorflow-text==2.12.0
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=5000

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2440, 3463, 1448, 765],
 [2440, 3463, 1448, 3689],
 [2440, 4236, 1448, 4024],
 [1726, 2106, 4732, 3679, 2798],
 [1726, 2106, 4732, 3679, 503],
 [662, 2440, 4929, 1448, 1837],
 [4865, 1185, 1475, 3679]]

In [7]:
## word Embedding Representation
from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='post',maxlen=sent_length)  ### padding='post' or 'pre'
print(embedded_docs)

[[2440 3463 1448  765    0    0    0    0]
 [2440 3463 1448 3689    0    0    0    0]
 [2440 4236 1448 4024    0    0    0    0]
 [1726 2106 4732 3679 2798    0    0    0]
 [1726 2106 4732 3679  503    0    0    0]
 [ 662 2440 4929 1448 1837    0    0    0]
 [4865 1185 1475 3679    0    0    0    0]]


In [9]:
## feature representation
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\Mahnoor\anaconda3\envs\py_env\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [11]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step


array([[[ 1.6070869e-02, -4.7694959e-02,  2.9686037e-02,  1.8230822e-02,
          3.0031092e-03, -4.1512679e-02,  1.0192763e-02, -2.3137391e-02,
          1.6088638e-02, -2.2836817e-02],
        [-2.4330342e-02,  3.4814741e-02,  4.0056992e-02,  2.1651957e-02,
         -3.3716083e-02,  2.8605353e-02,  4.9662117e-02, -2.6284708e-02,
          3.6058377e-02,  6.0789809e-03],
        [ 4.7743190e-02,  2.3575258e-02,  4.6266560e-02,  4.8633818e-02,
         -1.6006432e-02, -1.0168947e-02,  1.2562241e-02,  3.4571920e-02,
         -8.0745444e-03,  4.4375155e-02],
        [-2.6688183e-02, -1.9180967e-02, -4.3979347e-02, -4.6952676e-02,
         -9.9362135e-03,  4.6822801e-03,  4.0312912e-02,  2.9643659e-02,
          3.5778139e-02,  4.7023322e-02],
        [ 2.7275633e-02,  2.6520576e-02,  5.0042160e-03,  3.8549308e-02,
          1.5391473e-02,  3.7662014e-03, -2.6204705e-02,  2.7318969e-03,
          2.8575610e-02, -3.4282722e-02],
        [ 2.7275633e-02,  2.6520576e-02,  5.0042160e-03,  3.

In [12]:
embedded_docs[0]

array([2440, 3463, 1448,  765,    0,    0,    0,    0])

In [17]:
model.predict(embedded_docs)[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step


array([[ 0.01607087, -0.04769496,  0.02968604,  0.01823082,  0.00300311,
        -0.04151268,  0.01019276, -0.02313739,  0.01608864, -0.02283682],
       [-0.02433034,  0.03481474,  0.04005699,  0.02165196, -0.03371608,
         0.02860535,  0.04966212, -0.02628471,  0.03605838,  0.00607898],
       [ 0.04774319,  0.02357526,  0.04626656,  0.04863382, -0.01600643,
        -0.01016895,  0.01256224,  0.03457192, -0.00807454,  0.04437516],
       [-0.02668818, -0.01918097, -0.04397935, -0.04695268, -0.00993621,
         0.00468228,  0.04031291,  0.02964366,  0.03577814,  0.04702332],
       [ 0.02727563,  0.02652058,  0.00500422,  0.03854931,  0.01539147,
         0.0037662 , -0.02620471,  0.0027319 ,  0.02857561, -0.03428272],
       [ 0.02727563,  0.02652058,  0.00500422,  0.03854931,  0.01539147,
         0.0037662 , -0.02620471,  0.0027319 ,  0.02857561, -0.03428272],
       [ 0.02727563,  0.02652058,  0.00500422,  0.03854931,  0.01539147,
         0.0037662 , -0.02620471,  0.0027319 