## Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. If you are already familiar with MATLAB, you might find this [tutorial](http://wiki.scipy.org/NumPy_for_Matlab_Users) useful to get started with Numpy.

Also check this link: https://learnpython.com/blog/python-array-vs-list/

To use Numpy, we first need to import the `numpy` package:

In [ ]:
!pip install numpy

In [2]:
import numpy as np

### Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [ ]:
a = np.array([100, 200, 300])  # Create a rank 1 array

print(type(a))

print(a[0])
print(a[1])
print(a[2])

In [ ]:
print(a.shape)

In [ ]:
a[0] = 5  # Change an element of the array
print(a)

In [ ]:
a = np.array([[100, 200, 300]])
print(a.shape)

In [ ]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(b)

In [ ]:
print(b.shape)

In [ ]:
print(b[0, 0])
print(b[0, 1])
print(b[1, 0])

Numpy also provides many functions to create arrays:

In [49]:
a = np.zeros(shape=(2,2))  # Create an array of all zeros
print(a)

[[0. 0.]
 [0. 0.]]


In [50]:
b = np.ones(shape=(4,3))   # Create an array of all ones
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [52]:
c = np.full(shape=(2,2),fill_value=7) # Create a constant array
print(c)

[[7 7]
 [7 7]]


In [55]:
d = np.eye(N=3)        # Create a 3x3 identity matrix
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
e = np.random.random(size=(5,3)) # Create an array filled with random values
print(e)

In [ ]:
f = np.random.randint(25, 50, size=(4, 6))
print(f)

In [ ]:
g = np.arange(2,15,4)  # Create an array from 2 until 15 with steps 4
print(g)

### Array Indexing

Numpy offers several ways to index into arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [44]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

a = np.array([[100,200,300,400], [500,600,700,800], [900,1000,1100,1200]])
a

array([[ 100,  200,  300,  400],
       [ 500,  600,  700,  800],
       [ 900, 1000, 1100, 1200]])

In [45]:
a[1,2]

700

In [46]:
a[:,2:3]

array([[ 300],
       [ 700],
       [1100]])

In [47]:
a[0:4,2:3]

array([[ 300],
       [ 700],
       [1100]])

In [ ]:
a[1:2,:]

In [ ]:
a[:,3:4]

In [ ]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[0:2, 1:3]
print(b)

In [ ]:
#a[1:2,:]
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

In [ ]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1)
print(col_r1.shape)
print()
print(col_r2)
print(col_r2.shape)

In [ ]:
print(a)

In [ ]:
print(a+10)

In [ ]:
print(a*10)

In [ ]:
print(a-10)

In [ ]:
print(a/10)

Boolean array indexing: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [3]:
matrix1 = np.array([[1,2], [3, 4], [5, 6]])
print(matrix1)

[[1 2]
 [3 4]
 [5 6]]


In [4]:
matrix1.shape

(3, 2)

In [5]:
boolean_values_matrix = matrix1 > 2    # Find the elements of a that are bigger than 2;
                            # this returns a numpy array of Booleans of the same
                            # shape as a, where each slot of bool_idx tells
                            # whether that element of a is > 2.

print(boolean_values_matrix)

[[False False]
 [ True  True]
 [ True  True]]


In [6]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
matrix1[boolean_values_matrix]

array([3, 4, 5, 6])

In [16]:
x = np.where(boolean_values_matrix, matrix1, np.nan)
x

array([[nan, nan],
       [ 3.,  4.],
       [ 5.,  6.]])

In [18]:
x.shape

(3, 2)

In [19]:
x.reshape(2,3)

array([[nan, nan,  3.],
       [ 4.,  5.,  6.]])

In [21]:
x.reshape(6,1)

array([[nan],
       [nan],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.]])

In [22]:
x.reshape(1,6)

array([[nan, nan,  3.,  4.,  5.,  6.]])

For brevity we have left out a lot of details about numpy array indexing; if you want to know more you should read the documentation.

### Datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [23]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

# Print the type of each array
print(f"Type of x: {type(x)}")
print(f"Type of y: {type(y)}")
print(f"Type of z: {type(z)}")

# Print the dtype of each array
print(f"dtype of x: {x.dtype}")
print(f"dtype of y: {y.dtype}")
print(f"dtype of z: {z.dtype}")

Type of x: <class 'numpy.ndarray'>
Type of y: <class 'numpy.ndarray'>
Type of z: <class 'numpy.ndarray'>
dtype of x: int32
dtype of y: float64
dtype of z: int64


You can read all about numpy datatypes in the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

### Array Math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [27]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
z = np.array([[5,6],[7,8]])

In [25]:
print(x)

[[1. 2.]
 [3. 4.]]


In [26]:
print(y)

[[5. 6.]
 [7. 8.]]


In [28]:
print(z)

[[5 6]
 [7 8]]


In [29]:
# Elementwise sum
print(x + y)

[[ 6.  8.]
 [10. 12.]]


In [30]:
# Elementwise sum
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]


In [31]:
# Elementwise difference
print(x - y)

[[-4. -4.]
 [-4. -4.]]


In [32]:
# Elementwise difference
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]


In [33]:
# Elementwise product; 
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [34]:
# Elementwise division; 
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [35]:
v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; v.w=(9×11)+(10×12); both produce 219
print(v.dot(w))
print(np.dot(v, w))

219
219


You can also use the `@` operator which is equivalent to numpy's `dot` operator.

In [36]:
print(v @ w)

219


Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [41]:
x = np.array([[1,2],[3,4], [10,20]])
print(x)
print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

[[ 1  2]
 [ 3  4]
 [10 20]]
40
[14 26]
[ 3  7 30]


You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [42]:
print(x)
print("transpose\n", x.T)

[[ 1  2]
 [ 3  4]
 [10 20]]
transpose
 [[ 1  3 10]
 [ 2  4 20]]


In [43]:
v = np.array([[1,2,3]])
print(v )
print("transpose\n", v.T)

[[1 2 3]]
transpose
 [[1]
 [2]
 [3]]


### Array Statistics

In [ ]:
# Create a 1D array of 15 random integers between 1 and 100
array_2d = np.random.randint(1, 10, size=(5,5))
print(array_2d)

In [ ]:
# Calculate mean
mean_value = np.mean(array_2d)

# Calculate median
median_value = np.median(array_2d)

# Calculate standard deviation
std_dev = np.std(array_2d)

print(f"Mean: {mean_value}")
print(f"Median: {median_value}")
print(f"Standard Deviation: {std_dev}")

In [ ]:
# Find the minimum and maximum values overall
min_value = np.min(array_2d)
max_value = np.max(array_2d)

# Find the minimum and maximum values for each row
min_per_row = np.min(array_2d, axis=1)
max_per_row = np.max(array_2d, axis=1)

print(f"2D Array:\n{array_2d}")
print(f"Overall Minimum Value: {min_value}")
print(f"Overall Maximum Value: {max_value}")
print(f"Minimum Values per Row: {min_per_row}")
print(f"Maximum Values per Row: {max_per_row}")

In [ ]:
# Create a 1D array of random integers
array = np.random.randint(1, 100, 10)

# Calculate variance
variance = np.var(array)
std_dev = np.std(array)

print(f"Array: {array}")
print(f"Variance: {variance}")
print(f"Standard Deviation: {std_dev}")

## 1. Basic Array Creation

**Q1**: Create a 1D NumPy array containing the numbers from 0 to 9.

**Q2**: Create a 3x3 matrix filled with zeros.


**Q3**: Create a 4x4 matrix filled with the number 7.



## 2. Basic Array Operations

**Q4**: Create a 1D array of 5 elements and multiply each element by 2.



**Q5**: Create two 1D arrays and add them together.

**Q6**: Find the maximum value in a 1D array of 10 random integers.

## 3. Basic Indexing

**Q7**: Create a 1D array of 10 elements and print the 5th element.


**Q8**: Create a 2x3 matrix and print the element in the second row and third column.

**Q9**: Create a 1D array of 10 elements and print the first 3 elements.

## 4. Basic Reshaping

**Q10**: Create a 1D array of 12 elements and reshape it into a 3x4 matrix.



**Q11**: Create a 2x6 matrix and reshape it into a 3x4 matrix.



## 5. Basic Mathematical Operations

**Q12**: Create a 2x2 matrix and compute the sum of all its elements.

## 6. Array Slicing

**Q13**: Create a 1D array of 20 elements. Extract the elements from index 5 to 15.




**Q14**: Create a 3x5 matrix. Extract the first two rows and the last three columns.



**Q15**: Create a 5x5 matrix of random integers. Extract the diagonal elements.



## 7. Basic Array Statistics

**Q16**: Create a 1D array of 15 random integers between 1 and 100. Find the mean, median, and standard deviation of the array.



**Q17**: Create a 2D array of shape (4, 4) filled with random numbers. Find the minimum and maximum values for each row.



**Q18**: Create a 1D array of 10 random integers. Count how many elements are greater than 5.